version: '3.4'

services:
  weather.webapi:
    image: ${DOCKER_REGISTRY-}weatherwebapi
    build:
      context: .
      dockerfile: Weather.WebApi/Dockerfile
    depends_on:
      - "redisdb"

  redisdb:
    image: redis
    container_name: redisdb
    ports:
      - "6379:6379"

  postgres-db:
    container_name: postgres-db
    image: postgres
    ports:
      - "8081:5432"
    volumes:
      - C:\dockervolumes\postgresql:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
      POSTGRES_USER: "simha"
      POSTGRES_DB : "weather"

  postgresit-db:
    container_name: postgresit-db
    image: postgres
    ports:
      - "8082:5432"
    volumes:
      - C:\dockervolumesit\postgresql:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
      POSTGRES_USER: "simha"
      POSTGRES_DB : "weatherit"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "simha@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
      - postgresit-db