version: '3.4'

services:
  weather.webapi:
    image: ${DOCKER_REGISTRY-}weatherwebapi
    build:
      context: .
      dockerfile: Weather.WebApi/Dockerfile
    depends_on:
      - "redisdb"

  redisdb:
    image: redis
    container_name: redisdb
    ports:
      - "6379:6379"
